/*
 *
 *  * Copyright (c) 2025 Couchbase, Inc.
 *  *
 *  * Licensed under the Apache License, Version 2.0 (the "License");
 *  * you may not use this file except in compliance with the License.
 *  * You may obtain a copy of the License at
 *  *
 *  *    http://www.apache.org/licenses/LICENSE-2.0
 *  *
 *  * Unless required by applicable law or agreed to in writing, software
 *  * distributed under the License is distributed on an "AS IS" BASIS,
 *  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  * See the License for the specific language governing permissions and
 *  * limitations under the License.
 *
 */
// This file is @generated by prost-build.
/// Error is carried inside a response rather than replacing it. An empty string
/// means success, which is why the parse layer checks the string and not merely
/// the presence of the message.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Error {
    #[prost(string, required, tag = "1")]
    pub error: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TsConsistency {
    #[prost(uint32, repeated, packed = "false", tag = "1")]
    pub vbnos: ::prost::alloc::vec::Vec<u32>,
    #[prost(uint64, repeated, packed = "false", tag = "2")]
    pub seqnos: ::prost::alloc::vec::Vec<u64>,
    #[prost(uint64, repeated, packed = "false", tag = "3")]
    pub vbuuids: ::prost::alloc::vec::Vec<u64>,
    #[prost(uint64, optional, tag = "4")]
    pub crc64: ::core::option::Option<u64>,
}
/// Exactly one of the optional fields is set. Which one is what the payload
/// "is"; proto2 cannot express that, so parse::payload does.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryPayload {
    #[prost(uint32, required, tag = "1")]
    pub version: u32,
    #[prost(message, optional, tag = "4")]
    pub scan_request: ::core::option::Option<ScanRequest>,
    #[prost(message, optional, tag = "5")]
    pub scan_all_request: ::core::option::Option<ScanAllRequest>,
    #[prost(message, optional, tag = "6")]
    pub stream: ::core::option::Option<ResponseStream>,
    #[prost(message, optional, tag = "7")]
    pub count_request: ::core::option::Option<CountRequest>,
    #[prost(message, optional, tag = "8")]
    pub count_response: ::core::option::Option<CountResponse>,
    #[prost(message, optional, tag = "9")]
    pub end_stream: ::core::option::Option<EndStreamRequest>,
    #[prost(message, optional, tag = "10")]
    pub stream_end: ::core::option::Option<StreamEndResponse>,
    #[prost(message, optional, tag = "11")]
    pub helo_request: ::core::option::Option<HeloRequest>,
    #[prost(message, optional, tag = "12")]
    pub helo_response: ::core::option::Option<HeloResponse>,
    #[prost(message, optional, tag = "13")]
    pub auth_request: ::core::option::Option<AuthRequest>,
    #[prost(message, optional, tag = "14")]
    pub auth_response: ::core::option::Option<AuthResponse>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HeloRequest {
    #[prost(uint32, required, tag = "1")]
    pub version: u32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HeloResponse {
    #[prost(uint32, required, tag = "1")]
    pub version: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ScanRequest {
    #[prost(uint64, required, tag = "1")]
    pub defn_id: u64,
    #[prost(message, required, tag = "2")]
    pub span: Span,
    #[prost(bool, required, tag = "3")]
    pub distinct: bool,
    #[prost(int64, required, tag = "4")]
    pub limit: i64,
    #[prost(uint32, required, tag = "5")]
    pub cons: u32,
    #[prost(message, optional, tag = "6")]
    pub ts_vector: ::core::option::Option<TsConsistency>,
    #[prost(string, optional, tag = "7")]
    pub request_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(message, repeated, tag = "8")]
    pub scans: ::prost::alloc::vec::Vec<Scan>,
    #[prost(message, optional, tag = "9")]
    pub indexprojection: ::core::option::Option<IndexProjection>,
    #[prost(bool, optional, tag = "10")]
    pub reverse: ::core::option::Option<bool>,
    #[prost(int64, optional, tag = "11")]
    pub offset: ::core::option::Option<i64>,
    #[prost(int64, optional, tag = "12")]
    pub rollback_time: ::core::option::Option<i64>,
    #[prost(uint64, repeated, packed = "false", tag = "13")]
    pub partition_ids: ::prost::alloc::vec::Vec<u64>,
    #[prost(bool, optional, tag = "15")]
    pub sorted: ::core::option::Option<bool>,
    #[prost(uint32, optional, tag = "16")]
    pub data_enc_fmt: ::core::option::Option<u32>,
    #[prost(string, optional, tag = "17")]
    pub user: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(bool, optional, tag = "18")]
    pub skip_read_metering: ::core::option::Option<bool>,
    #[prost(int64, optional, tag = "20")]
    pub req_timeout: ::core::option::Option<i64>,
    #[prost(string, repeated, tag = "22")]
    pub index_key_names: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "23")]
    pub inline_filter: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ScanAllRequest {
    #[prost(uint64, required, tag = "1")]
    pub defn_id: u64,
    #[prost(int64, required, tag = "2")]
    pub limit: i64,
    #[prost(uint32, required, tag = "3")]
    pub cons: u32,
    #[prost(message, optional, tag = "4")]
    pub ts_vector: ::core::option::Option<TsConsistency>,
    #[prost(string, optional, tag = "5")]
    pub request_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int64, optional, tag = "6")]
    pub rollback_time: ::core::option::Option<i64>,
    #[prost(uint64, repeated, packed = "false", tag = "7")]
    pub partition_ids: ::prost::alloc::vec::Vec<u64>,
    #[prost(uint32, optional, tag = "8")]
    pub data_enc_fmt: ::core::option::Option<u32>,
    #[prost(string, optional, tag = "9")]
    pub user: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(bool, optional, tag = "10")]
    pub skip_read_metering: ::core::option::Option<bool>,
    #[prost(int64, optional, tag = "12")]
    pub req_timeout: ::core::option::Option<i64>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct EndStreamRequest {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ResponseStream {
    #[prost(message, repeated, tag = "1")]
    pub index_entries: ::prost::alloc::vec::Vec<IndexEntry>,
    #[prost(message, optional, tag = "2")]
    pub err: ::core::option::Option<Error>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StreamEndResponse {
    #[prost(message, optional, tag = "1")]
    pub err: ::core::option::Option<Error>,
    #[prost(uint64, optional, tag = "2")]
    pub read_units: ::core::option::Option<u64>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CountRequest {
    #[prost(uint64, required, tag = "1")]
    pub defn_id: u64,
    #[prost(message, required, tag = "2")]
    pub span: Span,
    #[prost(uint32, required, tag = "3")]
    pub cons: u32,
    #[prost(message, optional, tag = "4")]
    pub ts_vector: ::core::option::Option<TsConsistency>,
    #[prost(string, optional, tag = "5")]
    pub request_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(bool, optional, tag = "6")]
    pub distinct: ::core::option::Option<bool>,
    #[prost(message, repeated, tag = "7")]
    pub scans: ::prost::alloc::vec::Vec<Scan>,
    #[prost(int64, optional, tag = "8")]
    pub rollback_time: ::core::option::Option<i64>,
    #[prost(uint64, repeated, packed = "false", tag = "9")]
    pub partition_ids: ::prost::alloc::vec::Vec<u64>,
    #[prost(bool, optional, tag = "10")]
    pub skip_read_metering: ::core::option::Option<bool>,
    #[prost(string, optional, tag = "11")]
    pub user: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int64, optional, tag = "12")]
    pub req_timeout: ::core::option::Option<i64>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CountResponse {
    #[prost(int64, required, tag = "1")]
    pub count: i64,
    #[prost(message, optional, tag = "2")]
    pub err: ::core::option::Option<Error>,
}
/// Span is required on a ScanRequest even when `scans` carries the real bounds,
/// in which case it is sent empty. proto2 required means it cannot be omitted.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Span {
    #[prost(message, optional, tag = "1")]
    pub range: ::core::option::Option<Range>,
    #[prost(bytes = "vec", repeated, tag = "2")]
    pub equals: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Range {
    #[prost(bytes = "vec", optional, tag = "1")]
    pub low: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes = "vec", optional, tag = "2")]
    pub high: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(uint32, required, tag = "3")]
    pub inclusion: u32,
}
/// low and high are JSON, not collatejson — the indexer encodes them. An
/// unbounded end is omitted rather than encoded as a sentinel.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CompositeElementFilter {
    #[prost(bytes = "vec", optional, tag = "1")]
    pub low: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes = "vec", optional, tag = "2")]
    pub high: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(uint32, required, tag = "3")]
    pub inclusion: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Scan {
    #[prost(message, repeated, tag = "1")]
    pub filters: ::prost::alloc::vec::Vec<CompositeElementFilter>,
    #[prost(bytes = "vec", repeated, tag = "2")]
    pub equals: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct IndexProjection {
    #[prost(int64, repeated, packed = "false", tag = "1")]
    pub entry_keys: ::prost::alloc::vec::Vec<i64>,
    #[prost(bool, optional, tag = "2")]
    pub primary_key: ::core::option::Option<bool>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct IndexEntry {
    #[prost(bytes = "bytes", optional, tag = "1")]
    pub entry_key: ::core::option::Option<::prost::bytes::Bytes>,
    #[prost(bytes = "bytes", required, tag = "2")]
    pub primary_key: ::prost::bytes::Bytes,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AuthRequest {
    #[prost(string, required, tag = "1")]
    pub user: ::prost::alloc::string::String,
    #[prost(string, required, tag = "2")]
    pub pass: ::prost::alloc::string::String,
    #[prost(uint32, optional, tag = "3")]
    pub client_version: ::core::option::Option<u32>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AuthResponse {
    #[prost(uint32, required, tag = "1")]
    pub code: u32,
}
